# tmux.conf — entry point.

# --- Core General Settings ---
set -a terminal-features "tmux-256color:RGB"
set -g extended-keys on
set -g prefix C-SPACE
unbind C-b
bind C-SPACE send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -sg escape-time 0

# General Responsiveness & Mouse Defaults
set -g mouse on
set -g focus-events on
set -g set-clipboard on
set -g history-limit 1000000
set -g allow-passthrough on

# --- Load Config Modules ---
source-file ~/.config/tmux/keymaps.conf
source-file ~/.config/tmux/theme.conf
